db:
  container_name: db
  image: mongo
  net: ${NETWORK}
  
db2:
  container_name: db2
  image: mongo
  net: ${NETWORK}
  
db3:
  container_name: db3
  image: mongo
  net: ${NETWORK}
  
db4:
  container_name: db4
  image: mongo
  net: ${NETWORK}

nginx2:
  container_name: nginx2
  net: ${NETWORK}
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/public
  volumes_from:
    - liberty1
    - liberty2
    - liberty3
    - liberty4
    - liberty5

liberty1:
  container_name: liberty1
  net: ${NETWORK}
  build: ./acmeair-mainapp/
  environment:
    - LICENSE=accept

liberty2:
  container_name: liberty2
  net: ${NETWORK}
  build: ./acmeair-as/
  environment:
    - LICENSE=accept
  volumes_from:
    - db

liberty3:
  container_name: liberty3
  net: ${NETWORK}
  build: ./acmeair-bs/
  environment:
    - LICENSE=accept
  volumes_from:
    - db2

liberty4:
  container_name: liberty4
  net: ${NETWORK}
  build: ./acmeair-cs/
  environment:
    - LICENSE=accept
  volumes_from:
    - db3

liberty5:
  container_name: liberty5
  net: ${NETWORK}
  build: ./acmeair-fs/
  environment:
    - LICENSE=accept
  volumes_from:
    - db4
