db:
  image: mongo
  ports:
    - 27017:27017

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/public
  volumes_from:
    - liberty1
    - liberty2
    - liberty3
    - liberty4
    - liberty5
  links:
    - liberty1:liberty1
    - liberty2:liberty2
    - liberty3:liberty3
    - liberty4:liberty4
    - liberty5:liberty5

liberty1:
  build: ./acmeair-mainapp/
  environment:
    - LICENSE=accept
  ports:
    - 9090:9090

liberty2:
  build: ./acmeair-as/
  environment:
    - LICENSE=accept
  ports:
    - 9093:9093

liberty3:
  build: ./acmeair-bs/
  environment:
    - LICENSE=accept
  ports:
    - 9094:9094

liberty4:
  build: ./acmeair-cs/
  environment:
    - LICENSE=accept
  ports:
    - 9091:9091

liberty5:
  build: ./acmeair-fs/
  environment:
    - LICENSE=accept
  ports:
    - 9092:9092
